apiVersion: v1
kind: ReplicationController
metadata:
  name: guidesmiths-battle-deployment
spec:
  replicas: 0
  template:
    metadata:
      labels:
        role: guidesmiths-battle-deployment
    spec:
      containers:
      - name: guidesmiths-battle-deployment
        image: google/nodejs-hello
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
