@startuml

object Simulation

namespace Model {
    object Tank {
        x = ...
        y = ...
        angle = ...
    }
    object Bullet {
        x = ...
        y = ...
        angle = ...
    }
}

namespace View {
    object TankView
    object BulletView
}

Simulation --> View : updateViewLoop()
Simulation --> Model : updateModelLoop()

BulletView --> Bullet : getProperties()
TankView --> Tank : getProperties()

@enduml
